module.exports = {
   arrowParens: 'always',
   bracketSameLine: false,
   objectWrap: 'preserve',
   bracketSpacing: true,
   semi: true,
   experimentalOperatorPosition: 'end',
   experimentalTernaries: false,
   singleQuote: true,
   jsxSingleQuote: true,
   quoteProps: 'as-needed',
   trailingComma: 'all',
   singleAttributePerLine: false,
   htmlWhitespaceSensitivity: 'css',
   vueIndentScriptAndStyle: false,
   proseWrap: 'preserve',
   insertPragma: false,
   printWidth: 82,
   requirePragma: false,
   tabWidth: 3,
   useTabs: false,
   embeddedLanguageFormatting: 'auto',
};
